version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk@1.65.0
      - pip install --upgrade aws-cdk.aws_ecs_patterns==1.65.0
      - pip install --upgrade aws-cdk.aws_rds==1.65.0

  pre_build:
    commands:
      - ls
      - pwd
      - pip install -r requirements.txt
      - cd ..
      - mkdir deploytmp
      - cd deploytmp
      - cdk init --language=python
      - cdk bootstrap aws://${ACCOUNT_ID}/${AWS_REGION}
      - export CDK_DEFAULT_ACCOUNT=${ACCOUNT_ID}
      - export CDK_DEFAULT_REGION=${AWS_REGION}
      - unset AWS_ACCESS_KEY_ID ;
      - creds=$(mktemp -d)/creds.json ;
      - aws sts assume-role --role-arn arn:aws:iam::${ACCOUNT_ID}:role/ProvisioningRole --role-session-name "Deploy" > $creds ;
      - export AWS_ACCESS_KEY_ID=cat ${creds} | grep "AccessKeyId" | cut -d '"' -f 4
      - export AWS_SECRET_ACCESS_KEY=cat ${creds} | grep "SecretAccessKey" | cut -d '"' -f 4
      - export AWS_SECRET_ACCESS_KEY=cat ${creds} | grep "SecretAccessKey" | cut -d '"' -f 4
      - export AWS_SESSION_TOKEN=cat ${creds} | grep "SessionToken" | cut -d '"' -f 4

  build:
    commands:
      # copy deployment_stack to generate CDK deployment folder
      - pwd
      - cp -r ../faropt/* ./
      - ls
      - cdk deploy faropt --ec2creds
