version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk@1.56.0
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - ls
      - cdk bootstrap

     
  build:
    commands:
      # copy deployment_stack to generate CDK deployment folder
      - cdk deploy
