version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk@1.65.0
      - pip install --upgrade aws-cdk.aws_ecs_patterns==1.65.0
      - pip install --upgrade aws-cdk.aws_rds==1.65.0

  pre_build:
    commands:
      - ls
      - pwd
      - pip install -r requirements.txt
      - cd ..
      - mkdir deploytmp
      - cd deploytmp
      - cdk init --language=python
      - cdk bootstrap aws://${ACCOUNT_ID}/${AWS_REGION}
      - export CDK_DEFAULT_ACCOUNT=${ACCOUNT_ID}
      - export CDK_DEFAULT_REGION=${AWS_REGION}

  build:
    commands:
      # copy deployment_stack to generate CDK deployment folder
      - pwd
      - cp -r ../faropt/* ./
      - ls
      - cdk deploy faropt
