version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - ls
      - pwd
      - cd ..
      - mkdir -p deploytmp/faropt
      - cd deploytmp/faropt
      - ls
      - cdk init --language=python
     
  build:
    commands:
      # copy deployment_stack to generate CDK deployment folder
      - pwd
      - rm ./faropt/faropt_stack.py
      - mv ../../faropt/faropt_stack.py ./faropt/
      - cat ./faropt/faropt_stack.py
      - cdk deploy
