version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk@1.65.0
      - pip install --upgrade aws-cdk.aws_ecs_patterns==1.65.0
      - pip install --upgrade aws-cdk.aws_rds==1.65.0

  pre_build:
    commands:
      - ls
      - pwd
      - pip install -r requirements.txt
      - cd ..
      - mkdir -p deploytmp/faropt
      - cd deploytmp
      - cd faropt
      - cdk init --language=python
     
  build:
    commands:
      # copy deployment_stack to generate CDK deployment folder
      - pwd
      - cdk bootstrap aws://${ACCOUNT_ID}/${AWS_REGION}
      - cp -r ../faropt/faropt/faropt_stack.py ./faropt/faropt_stack.py
      - cat ./faropt/faropt_stack.py
      - cdk deploy
